#!/usr/bin/env python3

# Euphyllia : Yes, generated by IA (claude)
"""Fidorial registry-key generator (Paper-style).

Reads the legacy registries.json + datapack_registries.json ONE last time and
emits typed, compile-time registry keys into fidorial-api, plus a generated
runtime data table into fidorial-server. After running this the JSON files are
no longer needed at runtime and can be deleted.
"""
import json, os, re, sys

ROOT = sys.argv[1]
# Input snapshot lives with the generator (no longer a runtime resource).
SRV_RES = os.path.join(ROOT, "tool/registry-generator/data")
API = os.path.join(ROOT, "fidorial-api/src/main/java/fr/euphyllia/fidorial/api/registry")
SRV = os.path.join(ROOT, "fidorial-server/src/main/java/fr/euphyllia/fidorial/server/registry")

snap = json.load(open(os.path.join(SRV_RES, "registries.json")))
dyn  = json.load(open(os.path.join(SRV_RES, "datapack_registries.json")))

HEADER = "// GENERATED CODE - DO NOT EDIT.\n// Regenerate: python3 tool/registry-generator/generate.py <project-root>\n"

def strip(idv):        # minecraft:worldgen/biome -> worldgen/biome
    return idv.split(":", 1)[1]

def short(idv):        # worldgen/biome -> biome  (drop worldgen/ prefix like Paper)
    s = strip(idv)
    return s.split("/")[-1]

def pascal(s):
    return "".join(p.capitalize() for p in re.split(r"[/_]", s) if p)

def upper(s):
    return re.sub(r"[^A-Za-z0-9]", "_", s).upper()

def const_name(value):  # entry value part -> JAVA CONSTANT
    v = value.split(":", 1)[1] if ":" in value else value
    c = re.sub(r"[^A-Za-z0-9]", "_", v).upper()
    if c and c[0].isdigit():
        c = "_" + c
    return c

# --- which registries get the full typed-key treatment --------------------
# every dynamic (datapack) registry + attribute (named example, synced source)
specs = []  # (registry_id, ordered_entries, tags_or_None, source)
for rid, obj in dyn.items():
    specs.append((rid, list(obj["entries"]), obj.get("tags") or {}))
# attribute comes from the synced snapshot, ordered by protocol_id
attr = snap["minecraft:attribute"]["entries"]
attr_ordered = [k for k, _ in sorted(attr.items(), key=lambda e: e[1]["protocol_id"])]
specs.append(("minecraft:attribute", attr_ordered, {}))

# marker name / keys-class / registry-constant per registry
def names(rid):
    sh = short(rid)
    marker = pascal(sh)
    return marker, marker + "Keys", upper(sh)

# =========================================================================
# 1. fidorial-api : marker interfaces
# =========================================================================
data_dir = os.path.join(API, "data")
os.makedirs(data_dir, exist_ok=True)
markers = {}
for rid, _, _ in specs:
    marker, _, _ = names(rid)
    markers[marker] = rid
for marker, rid in sorted(markers.items()):
    with open(os.path.join(data_dir, marker + ".java"), "w") as f:
        f.write(HEADER)
        f.write("package fr.euphyllia.fidorial.api.registry.data;\n\n")
        f.write("/**\n * Marker type for entries of the {@code %s} registry.\n" % rid)
        f.write(" * Used only as the generic parameter of {@link fr.euphyllia.fidorial.api.registry.TypedKey}.\n */\n")
        f.write("public interface %s {\n}\n" % marker)

# =========================================================================
# 2. fidorial-api : RegistryKey constants  (hand-written base + generated block)
# =========================================================================
reg_lines = []
for rid, _, _ in specs:
    marker, _, cst = names(rid)
    reg_lines.append((cst, marker, strip(rid)))
reg_lines.sort()
with open(os.path.join(API, "RegistryKey.java"), "w") as f:
    f.write(HEADER)
    f.write("""package fr.euphyllia.fidorial.api.registry;

import fr.euphyllia.fidorial.api.registry.data.*;

import java.util.Objects;

/**
 * Identifies a Minecraft registry (e.g. {@code minecraft:worldgen/biome}).
 * The type parameter {@code T} is a phantom marker binding a registry to the
 * kind of value it holds, so a {@link TypedKey} cannot be pointed at the wrong
 * registry at compile time.
 *
 */
public record RegistryKey<T>(Key key) {

    public RegistryKey {
        Objects.requireNonNull(key, "key");
    }

    private static <T> RegistryKey<T> of(String path) {
        return new RegistryKey<>(Key.minecraft(path));
    }

    @Override
    public String toString() {
        return "RegistryKey[" + key + "]";
    }

""")
    for cst, marker, path in reg_lines:
        f.write('    public static final RegistryKey<%s> %s = of("%s");\n' % (marker, cst, path))
    f.write("}\n")

# =========================================================================
# 3. fidorial-api : generated *Keys holders
# =========================================================================
keys_dir = os.path.join(API, "keys")
os.makedirs(keys_dir, exist_ok=True)
for rid, entries, _ in specs:
    marker, cls, cst = names(rid)
    seen = {}
    with open(os.path.join(keys_dir, cls + ".java"), "w") as f:
        f.write(HEADER)
        f.write("package fr.euphyllia.fidorial.api.registry.keys;\n\n")
        f.write("import fr.euphyllia.fidorial.api.registry.Key;\n")
        f.write("import fr.euphyllia.fidorial.api.registry.RegistryKey;\n")
        f.write("import fr.euphyllia.fidorial.api.registry.TypedKey;\n")
        f.write("import fr.euphyllia.fidorial.api.registry.data.%s;\n\n" % marker)
        f.write("/**\n * Generated {@link TypedKey} constants for the {@code %s} registry.\n */\n" % rid)
        f.write("public final class %s {\n\n" % cls)
        f.write("    private %s() {\n    }\n\n" % cls)
        for e in entries:
            name = const_name(e)
            if name in seen:
                continue
            seen[name] = True
            value = e.split(":", 1)[1] if ":" in e else e
            f.write('    public static final TypedKey<%s> %s = create("%s");\n' % (marker, name, value))
        f.write("\n    private static TypedKey<%s> create(String value) {\n" % marker)
        f.write("        return TypedKey.create(RegistryKey.%s, Key.minecraft(value));\n    }\n}\n" % cst)

# =========================================================================
# 4. fidorial-server : generated runtime data table (replaces both JSON files)
# =========================================================================
def jstr(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

with open(os.path.join(SRV, "GeneratedRegistryData.java"), "w") as f:
    f.write(HEADER)
    f.write("""package fr.euphyllia.fidorial.server.registry;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Baked-in registry contents formerly loaded from datapack_registries.json.
 * Entry order is the network order (index == network id), and the registries
 * themselves are kept in datapack order so they are sent to the client in the
 * exact same sequence as before. Consumed by {@link Registries}.
 */
final class GeneratedRegistryData {

    private GeneratedRegistryData() {
    }

    static Map<String, Registry> dynamic() {
        return DYNAMIC;
    }

""")
    # emit one builder method per registry to keep methods small
    method_names = []
    for rid, entries, tags in [(r, e, t) for r, e, t in specs if r in dyn]:
        m = "r_" + re.sub(r"[^A-Za-z0-9]", "_", strip(rid))
        method_names.append((rid, m))
        f.write("    private static Registry %s() {\n" % m)
        f.write("        List<String> entries = List.of(\n")
        f.write(",\n".join("            " + jstr(e) for e in entries))
        f.write(");\n")
        if tags:
            f.write("        Map<String, List<String>> tags = Map.ofEntries(\n")
            tag_items = []
            for tname, tvals in tags.items():
                vals = ", ".join(jstr(v) for v in tvals)
                tag_items.append("            Map.entry(%s, List.of(%s))" % (jstr(tname), vals))
            f.write(",\n".join(tag_items))
            f.write(");\n")
            f.write("        return new Registry(%s, entries, tags);\n    }\n\n" % jstr(rid))
        else:
            f.write("        return new Registry(%s, entries, Map.of());\n    }\n\n" % jstr(rid))
    f.write("    private static final Map<String, Registry> DYNAMIC = build();\n\n")
    f.write("    private static Map<String, Registry> build() {\n")
    f.write("        Map<String, Registry> m = new LinkedHashMap<>();\n")
    for rid, m in method_names:
        f.write("        m.put(%s, %s());\n" % (jstr(rid), m))
    f.write("        return m;\n    }\n}\n")

print("generated: %d markers, %d registry-key constants, %d *Keys classes" %
      (len(markers), len(reg_lines), len(specs)))
print("dynamic registries baked:", sum(1 for r, _, _ in specs if r in dyn))
