package fr.euphyllia.fidorial.server.protocol.packet.clientbound.login;

import fr.euphyllia.fidorial.server.network.PacketBuffer;
import fr.euphyllia.fidorial.server.protocol.catalog.LoginClientboundPackets;
import fr.euphyllia.fidorial.server.protocol.packet.ClientboundPacket;

/**
 * <p>Used to implement a custom handshaking flow together with Login Plugin Response . Unlike plugin messages in "play" mode, these messages follow a lock-step request/response scheme, where the client is expected to respond to a request indicating whether it understood. The vanilla client always responds that it hasn't understood and sends an empty payload.</p>
 *
 * <p><b>Packet ID:</b> Login = 4 (0x04)</p>
 * <p><b>Source:</b> <a href="https://minecraft.wiki/w/Java_Edition_protocol/Packets#Login_Plugin_Request">Login Plugin Request</a></p>
 *
 * <h4>Packet structure</h4>
 * <table>
 *   <caption>Fields, in write/read order</caption>
 *   <thead>
 *     <tr><th>#</th><th>Field</th><th>Type</th><th>Description</th></tr>
 *   </thead>
 *   <tbody>
 *     <tr><td>0</td><td>Message ID</td><td>VarInt</td><td>Generated by the server - should be unique to the connection.</td></tr>
 *     <tr><td>1</td><td>Channel</td><td>Identifier</td><td>Name of the plugin channel used to send the data.</td></tr>
 *     <tr><td>2</td><td>Data</td><td>Varies</td><td>Any data, depending on the channel. Typically this would be a sequence of fields using standard data types, but some unofficial channels have unusual formats. There is no length prefix that applies to all channel types, but the format specific to the channel may or may not include one or more length prefixes (e.g. for strings). The vanilla client enforces a length limit of 1048576 bytes on this data, but only if the channel type is unrecognized (which is the case for all login plugin messages with a completely vanilla client).</td></tr>
 *   </tbody>
 * </table>
 */
public record ClientboundCustomQueryPacket(int transactionId, String channel, byte[] payload)
        implements ClientboundPacket {

    @Override
    public String name() {
        return LoginClientboundPackets.CUSTOM_QUERY;
    }

    @Override
    public void write(PacketBuffer buf) {
        buf.writeVarInt(transactionId)
                .writeIdentifier(channel)
                .writeRawBytes(payload);
    }
}
