package fr.euphyllia.fidorial.server.protocol.packet.clientbound.login;

import fr.euphyllia.fidorial.server.network.PacketBuffer;
import fr.euphyllia.fidorial.server.protocol.catalog.LoginClientboundPackets;
import fr.euphyllia.fidorial.server.protocol.packet.ClientboundPacket;

/**
 * <p>See protocol encryption for details.</p>
 *
 * <p><b>Packet ID:</b> Login = 1 (0x01)</p>
 * <p><b>Source:</b> <a href="https://minecraft.wiki/w/Java_Edition_protocol/Packets#Encryption_Request">Encryption Request</a></p>
 *
 * <h4>Packet structure</h4>
 * <table>
 *   <caption>Fields, in write/read order</caption>
 *   <thead>
 *     <tr><th>#</th><th>Field</th><th>Type</th><th>Description</th></tr>
 *   </thead>
 *   <tbody>
 *     <tr><td>0</td><td>Server ID</td><td>String (20)</td><td>Always empty when sent by the vanilla server.</td></tr>
 *     <tr><td>1</td><td>Public Key</td><td>Prefixed Array of Byte</td><td>The server's public key, in bytes.</td></tr>
 *     <tr><td>2</td><td>Verify Token</td><td>Prefixed Array of Byte</td><td>A sequence of random bytes generated by the server.</td></tr>
 *     <tr><td>3</td><td>Should authenticate</td><td>Boolean</td><td>Whether the client should attempt to authenticate through mojang servers .</td></tr>
 *   </tbody>
 * </table>
 */
public record ClientboundHelloPacket(String serverId, byte[] publicKey, byte[] verifyToken,
                                     boolean shouldAuthenticate) implements ClientboundPacket {

    @Override
    public String name() {
        return LoginClientboundPackets.HELLO;
    }

    @Override
    public void write(PacketBuffer buf) {
        buf.writeString(serverId)
                .writeByteArray(publicKey)
                .writeByteArray(verifyToken)
                .writeBoolean(shouldAuthenticate);
    }
}
