package fr.euphyllia.fidorial.server.protocol.packet.serverbound.play;

import fr.euphyllia.fidorial.server.network.PacketBuffer;
import fr.euphyllia.fidorial.server.protocol.packet.PacketListener;
import fr.euphyllia.fidorial.server.protocol.packet.ServerboundPacket;
import fr.euphyllia.fidorial.server.protocol.packet.listener.PlayPacketListener;
import net.kyori.adventure.text.Component;
import org.jspecify.annotations.Nullable;

import java.util.BitSet;

/**
 * <p>Used to send a chat message to the server.</p>
 * <p>The message may not be longer than 256 characters or else the server will kick the client. The server will broadcast a Player Chat Message packet with Chat Type minecraft:chat to all players that haven't disabled chat (including the player that sent the message). See Java Edition protocol/Chat#Processing chat for more information.</p>
 *
 * <p><b>Packet ID:</b> Play = 9 (0x09)</p>
 * <p><b>Source:</b> <a href="https://minecraft.wiki/w/Java_Edition_protocol/Packets#Chat_Message">Chat Message</a></p>
 *
 * <h4>Packet structure</h4>
 * <table>
 *   <caption>Fields, in write/read order</caption>
 *   <thead>
 *     <tr><th>#</th><th>Field</th><th>Type</th><th>Description</th></tr>
 *   </thead>
 *   <tbody>
 *     <tr><td>0</td><td>Message</td><td>String (256)</td><td>Content of the message</td></tr>
 *     <tr><td>1</td><td>Timestamp</td><td>Long</td><td>Number of milliseconds since the epoch (1 Jan 1970, midnight, UTC)</td></tr>
 *     <tr><td>2</td><td>Salt</td><td>Long</td><td>The salt used to verify the signature hash. Randomly generated by the client</td></tr>
 *     <tr><td>3</td><td>Signature</td><td>Prefixed Optional Byte Array (256)</td><td>The signature used to verify the chat message's authentication. When present, always 256 bytes and not length-prefixed. This is a SHA256 with RSA digital signature computed over the following: The number 1 as a 4-byte int. Always 00 00 00 01. The player's 16-byte UUID. The chat session (a 16-byte UUID randomly generated by the client). The index of the message within this chat session as a 4-byte int. First message is 0, next message is 1, etc. Incremented each time the client sends a chat message. The salt (from above) as an 8-byte long. The timestamp (from above) converted from milliseconds to seconds, so divide by 1000, as an 8-byte long. The length of the message in bytes (from above) as a 4-byte int. The message bytes. The number of messages in the last seen set, as a 4-byte int. Always in the range [0,20]. For each message in the last seen set, from oldest to newest, the 256-byte signature of that message. The client's chat private key is used for the message signature.</td></tr>
 *     <tr><td>4</td><td>Message Count</td><td>VarInt</td><td>Number of signed clientbound chat messages the client has seen from the server since the last serverbound chat message from this client. The server will use this to update its last seen list for the client.</td></tr>
 *     <tr><td>5</td><td>Acknowledged</td><td>Fixed BitSet (20)</td><td>Bitmask of which message signatures from the last seen set were used to sign this message. The most recent is the highest bit. If there are fewer than 20 messages in the last seen set, the lower bits will be zeros.</td></tr>
 *     <tr><td>6</td><td>Checksum</td><td>Byte</td><td>Checksum is computed over all the message signature checksums in the last seen set, from oldest to newest. Both the packet checksum and signature checksums use the same logic as Java's Arrays.hashCode(byte[]) implementation. The packet checksum additionally casts the resulting int to a byte, and if that byte is 0 returns 1, otherwise returns said byte</td></tr>
 *   </tbody>
 * </table>
 */
public record ServerboundChatPacket(
        Component message,
        long timestamp,
        long salt,
        byte @Nullable [] signature,
        int messageCount,
        BitSet acknowledged,
        byte checksum
) implements ServerboundPacket {

    private static final int MAX_LENGTH = 256;

    public static ServerboundChatPacket read(PacketBuffer buf) {
        Component message = buf.readComponent(MAX_LENGTH);
        long timestamp = buf.readLong();
        long salt = buf.readLong();
        byte[] sig = buf.readOptionalByteArray(MAX_LENGTH);
        int count = buf.readVarInt();
        BitSet acknowledged = buf.readFixedBitSet(20);
        byte checksum = buf.readByte();
        return new ServerboundChatPacket(
                message,
                timestamp,
                salt,
                sig,
                count,
                acknowledged,
                checksum
        );
    }

    @Override
    public void handle(PacketListener listener) {
        ((PlayPacketListener) listener).handleChat(this);
    }
}
