package fr.euphyllia.fidorial.gradle.libraries

import org.gradle.api.artifacts.component.ModuleComponentIdentifier
import java.io.File
import java.security.MessageDigest

/**
 * Line format shared by the server's `libraries.list` and every plugin's lock file:
 *
 * ```
 * group:artifact:version[:classifier] <sha256> <size>
 * ```
 */
internal object LibraryLists {

    fun header(what: String, taskName: String) =
        "# $what\n# Generated by the '$taskName' task — do not edit.\n"

    /**
     * Gradle hands us the module identifier without the classifier, so we recover it from
     * the file name. Matters for the native Netty transports, whose jars only differ by it.
     */
    fun coordinatesOf(identifier: ModuleComponentIdentifier, file: File): String {
        val base = "${identifier.module}-${identifier.version}"
        val name = file.name.removeSuffix(".jar")
        val classifier = if (name.length > base.length && name.startsWith("$base-")) {
            name.substring(base.length + 1)
        } else {
            null
        }
        return listOfNotNull(identifier.group, identifier.module, identifier.version, classifier)
            .joinToString(":")
    }

    private val UNIQUE_SNAPSHOT = Regex("""^(.*-\d{8}\.\d{6}-\d+)(?:-(.+))?$""")

    /**
     * For a `-SNAPSHOT` dependency, recovers the timestamped version from the file Gradle
     * resolved — `bytesocks-java-client-1.0-20260208.124123-2.jar` gives `1.0-20260208.124123-2`.
     *
     * Read off the file name rather than the component identifier on purpose: how Gradle
     * reports the version of a unique snapshot is an internal detail, the file name is not.
     * Returns null when Gradle kept the non-unique name, in which case the timestamp is
     * simply not knowable and the artifact has to be bundled.
     */
    fun timestampedVersionOf(module: String, file: File): String? {
        val stem = file.name.removeSuffix(".jar")
        if (!stem.startsWith("$module-")) return null
        val match = UNIQUE_SNAPSHOT.matchEntire(stem.removePrefix("$module-")) ?: return null
        return match.groupValues[1]
    }

    fun sha256(file: File): String {
        val digest = MessageDigest.getInstance("SHA-256")
        file.inputStream().buffered().use { input ->
            val buffer = ByteArray(64 * 1024)
            while (true) {
                val read = input.read(buffer)
                if (read < 0) break
                digest.update(buffer, 0, read)
            }
        }
        return digest.digest().joinToString("") { "%02x".format(it) }
    }
}
